# Generated by Django 3.2.13 on 2022-05-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('usd_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('eur_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('jpy_value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
