# Generated by Django 3.2.13 on 2022-05-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rates',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
