# Generated by Django 3.2.13 on 2022-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_base_rates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rates',
            name='eur_value',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='base_rates',
            name='jpy_value',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='base_rates',
            name='usd_value',
            field=models.CharField(max_length=5),
        ),
    ]
